# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'PayAsYouGo'
    subscriptionId: '17b39d17-d9ce-4edb-94cb-3d3a42ea4f3e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'Australia East'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/jhtut/AzureRmPipeline-repo/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName [EnterAProjectName]'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
